name: Code Coverage Report

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn -B clean package

    - name: Run Tests with JaCoCo
      run: mvn -B test jacoco:report

    - name: Generate Code Coverage Report
      uses: Flex/code-coverage-reporter-action@v4
      with:
        reporters: cobertura
        directory: target/site/cobertura
        github-token: ${{ secrets.GITHUB_TOKEN }}
